### ISSUE TITLE
Memory access error on linux-x64

### ISSUE THREAD

**Issue by renkei** [jesec/pkg-fetch#1]
I'm using Arch Linux (Kernel 5.10.16, glibc 2.33, libuv 1.41).

When I try `pkg -t node14-linux-x64` I'm getting a memory access error. The error occurs at the moment where my Bluetooth Node.js app tries to load the native module `binding.node` from the [bluetooth-hci-socket](https://www.npmjs.com/package/bluetooth-hci-socket) package (required by [noble](https://www.npmjs.com/package/noble)).

Both modules, `binding.node` and `usb_bindings.node` are placed in the same folder where also the `pkg` output file is located. My app starts fine (I get `console.log` outputs) until the `require` of the bluetooth module.

When I try `pkg -t node14-linuxstatic-x64` instead, I'm getting

```shell
pkg/prelude/bootstrap.js:1246
      throw error;
      ^

Error: Dynamic loading not supported
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.require (pkg/prelude/bootstrap.js:1227:31)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/snapshot/MyBluetoothApp/node_modules/bluetooth-hci-socket/lib/native.js:6:15)
    at Module._compile (pkg/prelude/bootstrap.js:1322:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)

```

My app compiles and starts fine with `npm install` and `npm start`, so the issue is pkg related.

**Comment by jesec** [comment]
I use some configure flags to drop features that are not needed in my projects. Native binding support is probably one of them.

**Comment by renkei** [comment]
Can you enable support for native modules, please? It should not have negative effects to you and other projects which doesn't make use of native modules but would help all other ones which require them.

**Comment by jesec** [comment]
PRs are welcome.

**Comment by sgoll** [comment]
I also have the problem that `pkg` builds (for target `node14.17.0-linuxstatic-armv7`) are built without errors but cannot be executed due to the error shown above.

**Comment by jesec** [comment]
Note that this fork is no longer supported. Please switch to vercel/pkg-fetch.
